Fix libsnmp-base compilation failure
libtool: link: gcc -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2 -fdebug-prefix-map=/sonic/src/snmpd/net-snmp-5.7.3+dfsg=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -DNETSNMP_USE_INLINE -Ulinux -Dlinux=linux -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -o .libs/snmptrapd .libs/snmptrapd.o -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-E  ./.libs/libnetsnmptrapd.so ../agent/.libs/libnetsnmpmibs.so ../agent/.libs/libnetsnmpagent.so ../snmplib/.libs/libnetsnmp.so -L/usr/lib/x86_64-linux-gnu/ -lmariadb -lnl-3 -lm -lwrap
/usr/bin/ld: ./.libs/libnetsnmptrapd.so: undefined reference to `load_defaults'
/usr/bin/ld: ./.libs/libnetsnmptrapd.so: undefined reference to `my_init'
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:297: snmptrapd] Error 1
make[5]: Leaving directory '/sonic/src/snmpd/net-snmp-5.7.3+dfsg/apps'
make[4]: *** [Makefile:657: subdirs] Error 1
make[4]: Leaving directory '/sonic/src/snmpd/net-snmp-5.7.3+dfsg'
dh_auto_build: make -j1 returned exit code 2
make[3]: *** [debian/rules:65: override_dh_auto_build] Error 2
make[3]: Leaving directory '/sonic/src/snmpd/net-snmp-5.7.3+dfsg'
make[2]: *** [debian/rules:41: binary] Error 2
make[2]: Leaving directory '/sonic/src/snmpd/net-snmp-5.7.3+dfsg'
make[1]: *** [Makefile:19: /sonic/target/debs/buster/libsnmp-base_5.7.3+dfsg-1.5_all.deb] Error 2

Fix: The definitions of load_defaults and my_init don't exist and hence
commenting out their use

Signed-off-by: Joyas Joseph <joyas_joseph@dell.com>