Fix issue: exception occurred during chassis object being destroyed
The following error message is observed during chassis object being destroyed
```
Exception ignored in: <function Chassis.__del__ at 0x7fd22165cd08>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/chassis.py", line 83, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
```

The chassis tries to import deinitialize_sdk_handle during being destroyed
for the purpose of releasing the sdk_handle.
However, to import another module during shutting down can causing error
because some of the fundamental infrastructure is no longer available.

To fix it, record the deinitialize_sdk_handle in chassis object when
sdk_handle is being initialized and call the deinitialize handler when
chassis object is being destroyed

Signed-off-by: Stephen Sun <stephens@nvidia.com>