container_checker on RP should check containers based on asic presence
    On Supervisor/RP card, some application containers may not run if
    the asic is not present due to a missing Fabric card. The container checker
    should skip those container instances.
    Container instances which run only if asic present: swss, syncd, lldp,
    teamd
    Exception: All instances of database and bgp containers run irrespective
    of asic presence.

Signed-off-by: anamehra anamehra@cisco.com