[docker-swss]: mount /var/log/swss into the docker
Fix the bug introduced by commit e6bb4b20a196f22a7e266f3e2de61df442ff09f4
The previous commit mount /var/log into the docker which override
the original /var/log directory structure, causing swss docker failed to
start due to following errors.

Error: The directory named as part of the path /var/log/supervisor/supervisord.log
does not exist.